FROM node:18-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходники
COPY . .

# Устанавливаем переменные окружения
ENV NODE_ENV=development

# Запуск Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]