FROM node:18-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем .env и исходники
COPY . .

# Устанавливаем nodemon
RUN npm install -g nodemon

# Переменные окружения
ENV NODE_ENV=development

# Запуск сервера
CMD ["npm", "run", "dev"]
