FROM node:18-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем .env и исходники
COPY . .

# Переменные окружения
ENV NODE_ENV=development

# Запуск сервера (с ts-node для разработки)
CMD ["npm", "run", "dev"]